### u1421126
**NumPy Indexing and Selection **

In [23]:
import numpy as np

In [24]:
arr = np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Indexing**

In [26]:
arr[0:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Broadcasting**

In [27]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [28]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [30]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [32]:
arr_copy = arr.copy()

arr_copy


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Indexing 2D array**

In [33]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[1]


array([20, 25, 30])

In [35]:
arr_2d[1][0]

20

In [36]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

**Fancy Indexing**

In [37]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Selection**

In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr>4

In [41]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])