### u1421126
** NumPy Indexing and Selection **

In [64]:
import numpy as np

In [65]:
arr = np.arange(0,11)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**  Indexing **

In [67]:
arr[0:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

** Broadcasting **

In [68]:
arr[0:5]=100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_copy = arr.copy()

arr_copy


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

** Indexing 2D array **

In [74]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[1]


array([20, 25, 30])

In [76]:
arr_2d[1][0]

20

In [77]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

** Fancy Indexing **

In [78]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

** Selection **

In [80]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [82]:
bool_arr = arr>4

In [83]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [84]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [85]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])