### u1421126
**NumPy** 

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**arange**

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**zeros and ones**

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**linspace**

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**Identity matrix**

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Random**

In [15]:
np.random.rand(2)

array([0.44171141, 0.35706846])

In [16]:
np.random.rand(5,5)

array([[0.14158562, 0.76225093, 0.27167363, 0.49654487, 0.92807674],
       [0.24747784, 0.65151446, 0.08407927, 0.42277946, 0.8071843 ],
       [0.16131428, 0.87478176, 0.5447708 , 0.88786885, 0.76195665],
       [0.98890981, 0.58113337, 0.6691984 , 0.2127151 , 0.23225546],
       [0.2426828 , 0.63646003, 0.65312644, 0.93056676, 0.14947434]])

**randn**

In [17]:
np.random.randn(2)

array([-0.265255  ,  0.13151257])

In [18]:
np.random.randn(5,5)

array([[ 0.62619449, -0.00487272, -1.16356093, -0.11754556, -0.3289928 ],
       [ 1.58853014,  1.63578964,  0.04697192,  1.96922965,  0.85868678],
       [-0.14268216, -0.26535382, -0.08714972, -1.22129311, -1.61557403],
       [ 0.30140662,  1.69722177,  0.88354106,  0.27779134,  1.59098904],
       [ 1.05641446,  1.21571427,  0.26632352,  0.8675085 , -0.34949536]])

**randint**

In [19]:
np.random.randint(1,100)

96

In [20]:
np.random.randint(1,100,10)

array([97, 56, 87, 89, 98,  9, 44, 47, 30, 21])

**Array Attributes and Methods**

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([44, 44, 24, 18, 28,  4, 18, 45,  5,  8])

**Reshape**

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**max,min,argmax,argmin**

In [25]:
ranarr

array([44, 44, 24, 18, 28,  4, 18, 45,  5,  8])

In [26]:
ranarr.max()

45

In [27]:
ranarr.argmax()

7

In [28]:
ranarr.min()

4

In [29]:
ranarr.argmin()

5

**Shape**

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)